Final_Project_ASP_MVC/Models/Admin.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Reflection.Metadata.Ecma335;

namespace Final_Project_ASP_MVC.Models
{
    public class Admin
    {
        public string? Password = "123";

        public string? UserName = "enter";
    }
}

Final_Project_ASP_MVC/Models/Animal.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Final_Project_ASP_MVC.Models
{
    public class Animal
    {
        //properties:

        [Display(Name = "Animal Id")]
        public int? AnimalId { get; set; }

        [StringLength(100)]
        [Required(ErrorMessage = "Please enter a name")]

        public string? Name { get; set; }
        [Range(0, 120)]
        [Required(ErrorMessage = "Please enter an age between 0-120")]
        public int? Age { get; set; }

        [Display(Name = "Picture Source")]
        [Required(ErrorMessage = "Please enter a Url that starts with https://")]
        [RegularExpression("^http(s)?://(.+)?$", ErrorMessage = "Please enter a Url that starts with https://")]
        public string? PictureSrc { get; set; }

        //[StringLength(200)]
        //[DataType(DataType.MultilineText)]
        //[Required(ErrorMessage = "Please enter a description the langth of max 200 chars")]
        public string? Description { get; set; }

        [Display(Name = "Category Id")]
        [Range(1, 5, ErrorMessage = "Please enter a number between 1-5")]
        [Required(ErrorMessage = "Please enter a category")]
        public int? CategoryId { get; set; }

        public ICollection<Comment> Comments { get; set; }

       public Category? Categories { get; set; }



    }
}

Final_Project_ASP_MVC/Models/Category.cs
using System;
namespace Final_Project_ASP_MVC.Models
{
    public class Category
    {
        public int? CategoryId { get; set; }
        public string? Name { get; set; }
        public ICollection<Animal>? Animals { get; set; }
    }
}

Final_Project_ASP_MVC/Models/Comment.cs
using System;
namespace Final_Project_ASP_MVC.Models
{
    public class Comment
    {
        public int CommentId { get; set; }
        public Animal? Animal { get; set; }
        public int AnimalId { get; set; }
        public string? Content { get; set; }

    }
}

Final_Project_ASP_MVC/Models/ErrorViewModel.cs
namespace Final_Project_ASP_MVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

}

Final_Project_ASP_MVC/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Final_Project_ASP_MVC.Models;
using Final_Project_ASP_MVC.Repositories;
using Microsoft.AspNetCore.Mvc;


namespace Final_Project_ASP_MVC.Controllers
{
    public class AdminController : Controller
    {
        AnimalRepository animalRepository;
        public AdminController(AnimalRepository animalRepository)
        {
            this.animalRepository = animalRepository;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Individual(string userName, string password)
        {
            if (userName == "enter" && password == "123")
            {
                return View("Individual", animalRepository.GetAllAnimals());
            }
            return View("Index");
        }
        public IActionResult Delete(int AnimalId)
        {
            animalRepository.Delete(AnimalId);
            return View("Individual", animalRepository.GetAllAnimals());
        }
        public IActionResult Edit(int animalId)
        {
            return View("Edit", animalRepository.ShowIndividualAnimal(animalId));
        }

        public IActionResult EditAge(int animalAge, int id)
        {
            animalRepository.EditAge(animalAge, id);
            return View("Edit", animalRepository.ShowIndividualAnimal(id));
        }
        public IActionResult EditDescription(string animalDescription, int id)
        {
            animalRepository.EditDescription(animalDescription, id);
            return View("Edit", animalRepository.ShowIndividualAnimal(id));

        }
        public IActionResult EditImgSrc(string AnimalImg, int id)
        {
            animalRepository.EditImgSrc(AnimalImg, id);
            return View("Edit", animalRepository.ShowIndividualAnimal(id));

        }
        public IActionResult EditName(string animalName, int id)
        {
            animalRepository.EditName(animalName, id);
            return View("Edit", animalRepository.ShowIndividualAnimal(id));

        }
        public IActionResult AddAnimal()
        {

            Animal animal = new Animal();
            List<Category> categories = new List<Category>();
            categories = animalRepository.AllCategories();
            ViewData["categories"] = categories;


            return View(animal);

        }
        public IActionResult AddEx(string Name, string Description, string PictureSrc, int Age, int CategoryId)
        {
            if (ModelState.IsValid)
            {
                animalRepository.AddAnimal(Name, Description, PictureSrc, Age, CategoryId);
                return RedirectToRoute(new { controller = "Admin", action = "Individual" });
            }
            else
                return View("AddAnimal");


        }


    }
}

Final_Project_ASP_MVC/Controllers/AnimalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Final_Project_ASP_MVC.Models;
using Final_Project_ASP_MVC.Repositories;
using Microsoft.AspNetCore.Mvc;


namespace Final_Project_ASP_MVC.Controllers
{
    public class AnimalController : Controller
    {
        AnimalRepository animalRepository;
        public AnimalController(AnimalRepository animalRepository)
        {
            this.animalRepository = animalRepository;
        }
        public IActionResult Index()
        {
           
            return View(animalRepository.GetAllAnimals());
        }
        public IActionResult Individual(int animalId)
        {
            return View(animalRepository.ShowIndividualAnimal(animalId));

        }
        public IActionResult AddComment(string Animal_Comment, int id)
        {
            var animal = animalRepository.AddComment(Animal_Comment, id);
            return View("Individual", animal);
        }

    }
}

Final_Project_ASP_MVC/Controllers/CatalogueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Final_Project_ASP_MVC.Repositories;
using Microsoft.AspNetCore.Mvc;


namespace Final_Project_ASP_MVC.Controllers
{
    public class CatalogueController : Controller
    {
        AnimalRepository? animalRepository;

        public CatalogueController(AnimalRepository animalRepository)
        {
            this.animalRepository = animalRepository;
        }

        public IActionResult Index()
        {
            return View(animalRepository!.GetListOfTypesAnimals());
        }
    }
}

Final_Project_ASP_MVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Final_Project_ASP_MVC.Models;
using Final_Project_ASP_MVC.Data;
using Final_Project_ASP_MVC.Repositories;

namespace Final_Project_ASP_MVC.Controllers;

public class HomeController : Controller
{
    private AnimalContext animalContext;
    AnimalRepository animalRepository;

    public HomeController(AnimalContext animalContext, AnimalRepository animalRepository)
    {
       this.animalContext = animalContext;
        this.animalRepository = animalRepository;
    }

    public IActionResult Index()
    {
        return View(animalRepository.MostComments());
    }
}

Final_Project_ASP_MVC/Views/Admin/AddAnimal.cshtml
@model Final_Project_ASP_MVC.Models.Animal
@{
    ViewData["Title"] = "Admin Page";
}

<div style="width: 30%;">

    <form asp-action="AddEx" class="py-5">

        <div class="form-group" style="margin-top: 20px;">
            <input asp-for="@Model.Name" class="form-control" placeholder="Add Name" required />
            @Html.ValidationMessageFor(model => model.Name)
            <span class="text-danger"></span>
        </div>
        <div class="form-group " style="margin-top: 20px;">
            <input asp-for="@Model.Age" class="form-control" placeholder="Add Age" required />
            @Html.ValidationMessageFor(model => model.Age)

            <span class="text-danger"></span>
        </div>

        <div class="form-group " style="margin-top: 20px;">
            <input asp-for="@Model.Description" class="form-control" placeholder="Add Description" required />
            @Html.ValidationMessageFor(model => model.Description)

            <span class="text-danger"></span>
        </div>

        <div class="form-group " style="margin-top: 20px;">
            <input asp-for="@Model.PictureSrc" class="form-control" placeholder="Add Image" required />
            @Html.ValidationMessageFor(model => model.PictureSrc)

            <span class="text-danger"></span>
        </div>
        <div>
            <input asp-for="Age" />
            <span asp-validation-for="Age"></span>
        </div>

        <select name="CategoryId" style="text-align: center;">
            <option value="2">Birds</option>

            <option value="1">Mammals</option>

            <option value="3">Fish</option>

            <option value="4">Amphibians</option>


            <option value="5">reptiles</option>
        </select>


        <div class="form-group">
            <button style="margin-left:25%; margin-top:50px;" type="submit" class="btn btn-lg btn-success btn-block">Add Animal</button>
        </div>


    </form>


</div>

Final_Project_ASP_MVC/Views/Admin/Edit.cshtml
@model Final_Project_ASP_MVC.Models.Animal


<div class="card-collection" style="width: fit-content;">


    <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="@Model.PictureSrc" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">Name: @Model.Name</h5>
            <h5 class="card-title">Age: @Model.Age</h5>
            <h5 class="card-title">Description: @Model.Description</h5>
        </div>
    </div>




    <div class="edit-botton">

        <h3 class="card-title" style="margin: auto;">Fill for Edit</h3>

        @using (Html.BeginForm("EditAge", "Admin", new { id = Model.AnimalId }, FormMethod.Post))
        {
            @Html.TextBox("animalAge", null, new { id = Model.AnimalId, @placeholder = "Change Age" })
            <input type="submit" value="Edit Age" />
        }

        @using (Html.BeginForm("EditDescription", "Admin", new { id = Model.AnimalId }, FormMethod.Post))
        {
            @Html.TextBox("animalDescription", null, new { id = Model.AnimalId, @placeholder = "Change Description" })
            <input type="submit" value="Edit Description" />
        }

        @using (Html.BeginForm("EditPictureSrc", "Admin", new { id = Model.AnimalId }, FormMethod.Post))
        {
            @Html.TextBox("AnimalImg", null, new { id = Model.AnimalId, @placeholder = "Change Picture Src" })
            <input type="submit" value="Edit Picture Src" />
        }

        @using (Html.BeginForm("EditName", "Admin", new { id = Model.AnimalId }, FormMethod.Post))
        {
            @Html.TextBox("animalName", null, new { id = Model.AnimalId, @placeholder = "Change Name" })
            <input type="submit" value="Edit Name" />
        }
    </div>
</div>

Final_Project_ASP_MVC/Views/Admin/Index.cshtml
<head>
    <link type="text/css" rel="stylesheet" href="~/site.css" />
</head>

<body>

    @model Final_Project_ASP_MVC.Models.Admin
    @{
        ViewData["Title"] = "Admin Page";
    }

    <div class="container border" style="padding: 20px; width: 25em; background-color: #395B64; "  >

        <form method="post" asp-action="Individual" asp-controller="Admin" class="py-5">
            <div class="d-flex justify-content-center">
                <i class="icon-map-marker icon-4x text-success"></i>
            </div>
            <div class="d-flex justify-content-center">
                <h1 class="h3 mb-3 font-weight-normal" style="color: #FEFBF6;" >Please sign in</h1>
                <div class="text-danger"></div>
            </div>
            <div class="form-group" style="margin-top: 20px;">
                <input asp-for="@Model.UserName" class="form-control" placeholder="User Name" required />
                @Html.ValidationMessageFor(model => model.UserName)
                <span class="text-danger"></span>
            </div>
            <div class="form-group " style="margin-top: 20px;">
                <input asp-for="@Model.Password" class="form-control" placeholder="Password" type="password" required />
                @Html.ValidationMessageFor(model => model.Password)

                <span class="text-danger"></span>
            </div>

            <div class="form-group">
                <button style="margin-left:40%; margin-top:50px;" type="submit" class="btn btn-lg btn-success btn-block">Login</button>
            </div>
        </form>

    </div>
</body>

Final_Project_ASP_MVC/Views/Admin/Individual.cshtml
@model IEnumerable<Final_Project_ASP_MVC.Models.Animal>
@{
    ViewData["Title"] = "Animal Page";
}




<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap Table with Add and Delete Row Feature</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round|Open+Sans">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

   
    <style>

    @*Nice Table Edit Add Delete!!!!!!!!*@

        body {
            color: #404E67;
            background: #F5F7FA;
            font-family: 'Open Sans', sans-serif;
        }

        .table-wrapper {
            width: 700px;
            margin: 30px auto;
            background: #fff;
            padding: 20px;
            box-shadow: 0 1px 1px rgba(0,0,0,.05);
        }

        .table-title {
            padding-bottom: 10px;
            margin: 0 0 10px;
        }

            .table-title h2 {
                margin: 6px 0 0;
                font-size: 22px;
            }

            .table-title .add-new {
                float: right;
                height: 30px;
                font-weight: bold;
                font-size: 12px;
                text-shadow: none;
                min-width: 100px;
                border-radius: 50px;
                line-height: 13px;
            }

                .table-title .add-new i {
                    margin-right: 4px;
                }

        table.table {
            table-layout: fixed;
        }

            table.table tr th, table.table tr td {
                border-color: #e9e9e9;
            }

            table.table th i {
                font-size: 13px;
                margin: 0 5px;
                cursor: pointer;
            }

            table.table th:last-child {
                width: 100px;
            }

            table.table td a {
                cursor: pointer;
                display: inline-block;
                margin: 0 5px;
                min-width: 24px;
            }

                table.table td a.add {
                    color: #27C46B;
                }

                table.table td a.edit {
                    color: #FFC107;
                }

                table.table td a.delete {
                    color: #E34724;
                }

            table.table td i {
                font-size: 19px;
            }

            table.table td a.add i {
                font-size: 24px;
                margin-right: -1px;
                position: relative;
                top: 3px;
            }

            table.table .form-control {
                height: 32px;
                line-height: 32px;
                box-shadow: none;
                border-radius: 2px;
            }

                table.table .form-control.error {
                    border-color: #f50000;
                }

            table.table td .add {
                display: none;
            }

            @*Nice Table Edit Add Delete!!!!!!!!*@

           


    </style>
    <script>

        @* Nice Table Edit Add Delete!!!!!!!! *@

        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
            var actions = $("table td:last-child").html();
            // Append table with add row form on add new button click
            $(".add-new").click(function () {
                $(this).attr("disabled", "disabled");
                var index = $("table tbody tr:last-child").index();
                var row = '<tr>' +
                    '<td><input type="text" class="form-control" name="name" id="name"></td>' +
                    '<td><input type="text" class="form-control" name="department" id="department"></td>' +
                    '<td><input type="text" class="form-control" name="phone" id="phone"></td>' +
                    '<td>' + actions + '</td>' +
                    '</tr>';
                $("table").append(row);
                $("table tbody tr").eq(index + 1).find(".add, .edit").toggle();
                $('[data-toggle="tooltip"]').tooltip();
            });
            // Add row on add button click
            $(document).on("click", ".add", function () {
                var empty = false;
                var input = $(this).parents("tr").find('input[type="text"]');
                input.each(function () {
                    if (!$(this).val()) {
                        $(this).addClass("error");
                        empty = true;
                    } else {
                        $(this).removeClass("error");
                    }
                });
                $(this).parents("tr").find(".error").first().focus();
                if (!empty) {
                    input.each(function () {
                        $(this).parent("td").html($(this).val());
                    });
                    $(this).parents("tr").find(".add, .edit").toggle();
                    $(".add-new").removeAttr("disabled");
                }
            });
            // Edit row on edit button click
            $(document).on("click", ".edit", function () {
                $(this).parents("tr").find("td:not(:last-child)").each(function () {
                    $(this).html('<input type="text" class="form-control" value="' + $(this).text() + '">');
                });
                $(this).parents("tr").find(".add, .edit").toggle();
                $(".add-new").attr("disabled", "disabled");
            });
            // Delete row on delete button click
            $(document).on("click", ".delete", function () {
                $(this).parents("tr").remove();
                $(".add-new").removeAttr("disabled");
            });
        });

        @* Nice Table Edit Add Delete!!!!!!!! *@



    </script>
</head>
<body>
    <div class="container">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-8"><h2>Admin  <b>Actions</b></h2></div>
                    <div class="col-sm-4">
                        <button type="button" class="btn btn-info add-new" onclick="location.href='@Url.Action("AddAnimal", "Admin")'"><i class="fa fa-plus"></i> Add New</button>
                    </div>
                </div>
            </div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var animal in Model)
                    {
                        <tr>
                            <td>@animal.Name</td>
                            <td>
                                <a class="add" title="Add" asp-controller="Admin" asp-action="Add" data-toggle="tooltip"><i class="material-icons">&#xE03B;</i></a>
                                <a class="edit" title="Edit" asp-route-animalId="@animal.AnimalId" asp-controller="Admin" asp-action="Edit" data-toggle="tooltip"><i class="material-icons">&#xE254;</i></a>
                                <a class="delete" title="Delete" asp-route-animalId="@animal.AnimalId" asp-controller="Admin" asp-action="Delete" data-toggle="tooltip"><i class="material-icons">&#xE872;</i></a>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>



</body>
</html>

Final_Project_ASP_MVC/Views/Animal/Index.cshtml
<head>
    <link type="text/css" rel="stylesheet" href="~/site.css" />
</head>

<body>

    @model IEnumerable<Final_Project_ASP_MVC.Models.Animal>
    @{
        ViewData["Title"] = "Animal Page";
    }

    <div class="text-center">
        <h1 class="display-4">Animal Collection</h1>


    </div>

    <div class="card-collection">


    @foreach (var animal in Model)
    {

        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="@animal.PictureSrc" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">@animal.Name</h5>
                <p class="card-text-age">Age: @animal.Age</p>
                <p class="card-text">@animal.Description</p>
                <a class="btn btn-primary" asp-route-animalId="@animal.AnimalId" asp-controller="Animal" asp-action="individual">Show Details</a>
            </div>
        </div>
    }

    </div>
   


</body>

Final_Project_ASP_MVC/Views/Animal/Individual.cshtml
@model Final_Project_ASP_MVC.Models.Animal

<div>

        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="@Model.PictureSrc" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">@Model.Name</h5>
                @foreach (var comment in Model.Comments!)
                {
                    <p>@comment.Content!</p>
                }
            </div>
        </div>

</div>


@using (Html.BeginForm("AddComment", "Animal", new { id = Model.AnimalId }, FormMethod.Post))
{
    @Html.TextBox("Animal_Comment", null, new { id = Model.AnimalId, @placeholder = "Leave Comment Here" })
    <input type="submit" value="Add Comment" />
}

Final_Project_ASP_MVC/Views/Home/Index.cshtml
@model IEnumerable<Final_Project_ASP_MVC.Models.Animal>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome!</h1>
    <h2>Our Top 2 Commented Animals In Our Website!</h2>

    <div class="card-collection">


        @foreach (var animal in Model)
        {

            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="@animal.PictureSrc" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">@animal.Name</h5>
                </div>
            </div>
        }

    </div>


</div>

Final_Project_ASP_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Final_Project_ASP_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Final_Project_ASP_MVC.styles.css" asp-append-version="true" />

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="plugins/summernote/summernote-bs4.min.css">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-#F1EFDC border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catalogue" asp-action="index">Catalogue</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Animal" asp-action="index">Animal</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Final_Project_ASP_MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>